baseURL = 'https://oakcat.github.io/'
languageCode = 'zh-cn'
DefaultContentLanguage = "zh-cn"
title = 'Oakcat - 思辨人生，窥探宇宙奥秘'
enableRobotsTXT = true
enableEmoji = true
theme = "hulga"
hasCJKLanguage = true
paginate = 10
[params.social]
  GitHub = "/oakcat"
  Email   = "2273716951@qq.com"
[params.gitalk]
owner = "oakcat"       # 你的GitHub ID       
repo = "blog"        # 博客网址    
labels = "gitalk"
[Permalinks]
  posts = "/:year/:month/:title/"
[params]
  # show in HTML meta tag
  author = "oakcat"
  keywords = "My Living and life"
  description = "oakcat's blog, learning life"

  # change bulma's primary color
  primaryColor = "#9370DB"

  # subtitle on homepage
  subtitle = "探寻真理，超越人生，拥抱宇宙"

  # copyright text on footer
  copyright = "Copyright © 2023 oakcat. All rights reserved."

  # enable katex rendering on every post page, default false
  math = false

  # enable postcss, mainly for css purge (129kB->20kB->4.8kB gzipped, but this makes build slower), default false
  postcss = true

  # enable showing content summary below post title in home page, default false
  showSummary = true

  # set paginate on taxonomy term page (tags or categories), default 10
  termPaginate = 3

  # enable toc on every post page, default false
  toc = true

  # enable TOC auto collapse, default false
  autoCollapseToc = true

  # enable prefers-color-scheme:dark, default false
  darkMedia = true

  # enable hero section's is-bold effect, default false
  heroBold = false

  # enable hero section that looks like steam deck's home page, default false
  heroSteamDeck = false

  # enable PWA, prepare your icons and DON'T forget to modify manifest.json, default false
  pwa = true

  # disable jsdelivr cdn, default false
  noCDN = false

[author]
  name = "oakcat"

  [params.publisher]
    name = "oakcat"

    [params.publisher.logo]
      url = "logo.png"
      width = 127
      height = 40

  [params.logo]
    url = "logo.png"
    width = 127
    height = 40


# to enable different hightlight themes in light/dark mode 
[markup]
  [markup.highlight]
    noClasses = false

[menu]
  [[menu.main]]
    identifier = "index"
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    identifier = "categories"
    name = "类别"
    url = "/categories/"
    weight = 4
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 5

[taxonomies]
category = "categories"
tag = "tags"

